apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

nameSuffix: -prod

images:
  - name: runtime-metrics-exporter:latest
    newName: ghcr.io/ionelpopjara/moogle/runtime-metrics-exporter
    newTag: latest

patches:
  - target:
      kind: Ingress
      name: moogle-ingress
    patch: |-
      - op: add
        path: /metadata/annotations/cert-manager.io~1cluster-issuer
        value: letsencrypt-prod
      - op: add
        path: /metadata/annotations/nginx.ingress.kubernetes.io~1force-ssl-redirect
        value: "true"
      - op: replace
        path: /spec/rules/0/host
        value: moogle.example.com
      - op: add
        path: /spec/tls
        value:
          - hosts:
              - moogle.example.com
            secretName: moogle-prod-tls
  - target:
      kind: Deployment
      name: query-engine
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
  - target:
      kind: Deployment
      name: query-engine-caddy
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
  - target:
      kind: ExternalSecret
      name: moogle-runtime-secrets
    patch: |-
      - op: replace
        path: /spec/secretStoreRef/name
        value: vault-backend-prod
      - op: replace
        path: /spec/data
        value:
          - secretKey: PIPELINE_REDIS_URL
            remoteRef:
              key: moogle/prod/shared
              property: PIPELINE_REDIS_URL
          - secretKey: PIPELINE_REDIS_PASSWORD
            remoteRef:
              key: moogle/prod/shared
              property: PIPELINE_REDIS_PASSWORD
          - secretKey: QUERY_REDIS_URL
            remoteRef:
              key: moogle/prod/shared
              property: QUERY_REDIS_URL
          - secretKey: CACHE_REDIS_URL
            remoteRef:
              key: moogle/prod/shared
              property: CACHE_REDIS_URL
          - secretKey: MONGODB_URI
            remoteRef:
              key: moogle/prod/shared
              property: MONGODB_URI
          - secretKey: MONGODB_DATABASE
            remoteRef:
              key: moogle/prod/shared
              property: MONGODB_DATABASE
          - secretKey: MONGODB_QUERY_USERNAME
            remoteRef:
              key: moogle/prod/shared
              property: MONGODB_QUERY_USERNAME
          - secretKey: MONGODB_QUERY_PASSWORD
            remoteRef:
              key: moogle/prod/shared
              property: MONGODB_QUERY_PASSWORD
          - secretKey: MONGO_HOST
            remoteRef:
              key: moogle/prod/shared
              property: MONGO_HOST
          - secretKey: MONGO_PORT
            remoteRef:
              key: moogle/prod/shared
              property: MONGO_PORT
          - secretKey: MONGO_DB
            remoteRef:
              key: moogle/prod/shared
              property: MONGO_DB
          - secretKey: MONGO_USERNAME
            remoteRef:
              key: moogle/prod/shared
              property: MONGO_USERNAME
          - secretKey: MONGO_PASSWORD
            remoteRef:
              key: moogle/prod/shared
              property: MONGO_PASSWORD
          - secretKey: MONGO_INITDB_ROOT_USERNAME
            remoteRef:
              key: moogle/prod/shared
              property: MONGO_INITDB_ROOT_USERNAME
          - secretKey: MONGO_INITDB_ROOT_PASSWORD
            remoteRef:
              key: moogle/prod/shared
              property: MONGO_INITDB_ROOT_PASSWORD
          - secretKey: APP_KEY
            remoteRef:
              key: moogle/prod/query-engine
              property: APP_KEY
          - secretKey: APP_URL
            remoteRef:
              key: moogle/prod/query-engine
              property: APP_URL
