apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: moogle

resources:
  - serviceaccount-prometheus-local.yaml
  - role-prometheus-local.yaml
  - rolebinding-prometheus-local.yaml
  - prometheus-local.yaml
  - servicemonitor-query-engine-metrics.yaml
  - servicemonitor-runtime-metrics.yaml
  - servicemonitor-spider-metrics.yaml
