apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-local
  labels:
    app.kubernetes.io/name: prometheus-local
rules:
  - apiGroups: [""]
    resources:
      - services
      - endpoints
      - pods
    verbs:
      - get
      - list
      - watch
