apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-local
  labels:
    app.kubernetes.io/name: prometheus-local
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-local
subjects:
  - kind: ServiceAccount
    name: prometheus-local
