apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: spider-metrics
  labels:
    app.kubernetes.io/name: spider-metrics
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: spider-metrics
  namespaceSelector:
    matchNames:
      - moogle
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
