services:
  spider-service:
    build: .
    # image: ghcr.io/ionelpopjara/moogle/spider:latest
    env_file: "variables.env"
    init: true
    restart: unless-stopped
    stop_grace_period: 30s
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      replicas: 1
