services:
  page-rank-service:
    build: .
    # image: ghcr.io/ionelpopjara/moogle/page-rank:latest
    env_file: "variables.env"
    init: true
    restart: "no"
    stop_grace_period: 30s
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      replicas: 1
