apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: moogle-runtime-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: vault-backend
  target:
    name: moogle-runtime-secrets
    creationPolicy: Owner
  data:
    - secretKey: PIPELINE_REDIS_URL
      remoteRef:
        key: moogle/dev/shared
        property: PIPELINE_REDIS_URL
    - secretKey: PIPELINE_REDIS_PASSWORD
      remoteRef:
        key: moogle/dev/shared
        property: PIPELINE_REDIS_PASSWORD
    - secretKey: QUERY_REDIS_URL
      remoteRef:
        key: moogle/dev/shared
        property: QUERY_REDIS_URL
    - secretKey: CACHE_REDIS_URL
      remoteRef:
        key: moogle/dev/shared
        property: CACHE_REDIS_URL
    - secretKey: MONGODB_URI
      remoteRef:
        key: moogle/dev/shared
        property: MONGODB_URI
    - secretKey: MONGODB_DATABASE
      remoteRef:
        key: moogle/dev/shared
        property: MONGODB_DATABASE
    - secretKey: MONGODB_QUERY_USERNAME
      remoteRef:
        key: moogle/dev/shared
        property: MONGODB_QUERY_USERNAME
    - secretKey: MONGODB_QUERY_PASSWORD
      remoteRef:
        key: moogle/dev/shared
        property: MONGODB_QUERY_PASSWORD
    - secretKey: MONGO_HOST
      remoteRef:
        key: moogle/dev/shared
        property: MONGO_HOST
    - secretKey: MONGO_PORT
      remoteRef:
        key: moogle/dev/shared
        property: MONGO_PORT
    - secretKey: MONGO_DB
      remoteRef:
        key: moogle/dev/shared
        property: MONGO_DB
    - secretKey: MONGO_USERNAME
      remoteRef:
        key: moogle/dev/shared
        property: MONGO_USERNAME
    - secretKey: MONGO_PASSWORD
      remoteRef:
        key: moogle/dev/shared
        property: MONGO_PASSWORD
    - secretKey: MONGO_INITDB_ROOT_USERNAME
      remoteRef:
        key: moogle/dev/shared
        property: MONGO_INITDB_ROOT_USERNAME
    - secretKey: MONGO_INITDB_ROOT_PASSWORD
      remoteRef:
        key: moogle/dev/shared
        property: MONGO_INITDB_ROOT_PASSWORD
    - secretKey: APP_KEY
      remoteRef:
        key: moogle/dev/query-engine
        property: APP_KEY
    - secretKey: APP_URL
      remoteRef:
        key: moogle/dev/query-engine
        property: APP_URL
