apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: moogle

resources:
  - namespace.yaml
  - configmap.yaml
  - configmap-caddy.yaml
  - deployment-query-engine.yaml
  - service-query-engine.yaml
  - deployment-caddy.yaml
  - service-caddy.yaml
  - deployment-query-redis.yaml
  - service-query-redis.yaml
  - deployment-pipeline-redis.yaml
  - service-pipeline-redis.yaml
  - ingress.yaml
