apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

nameSuffix: -dev

images:
  - name: runtime-metrics-exporter:latest
    newName: ghcr.io/ionelpopjara/moogle/runtime-metrics-exporter
    newTag: latest

patches:
  - target:
      kind: Ingress
      name: moogle-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: dev.moogle.local
